name: github_action

x-application-server: &application-container-settings
  build:
    context: .
    dockerfile: ApiDockerfile

services:
  app-1:
    container_name: app-1
    privileged: true
    ports:
      - '8081:8080'
    <<: *application-container-settings
    app-2:
      container_name: app-2
      privileged: true
      ports:
        - '8082:8080'
      <<: *application-container-settings

volumes:
  postgresql_data:

networks:
  shinemuscat:
    external: true